### ISSUE TITLE
Support for other mapping formats?

### ISSUE THREAD

**Issue by TheKodeToad** [QuiltMC/tiny-remapper#9]
Would be pretty nice :3
but it's called tiny-remapper so this may be out of scope

**Comment by TheKodeToad** [comment]
I've just liked the idea of something similar to tiny remapper but not so specific for a while

**Comment by OroArmor** [comment]
Once QuiltMC/quilt-mapping-tools is finalized, this wont be a problem as everything will be integrated there. This repository tries to stay mostly synced with Fabric's and this would just add extra complexity
